### ISSUE TITLE
Support For over objects

### ISSUE THREAD

**Issue by NullEntity** [valtech-au/jsx-control-statements#11]
I was expecting For to be able to iterate over objects and their keys/values, but it doesn't look like that's the case. Could you add support for this?

**Comment by helarqjsc** [comment]
Good idea. It could be compiled to something like this:
```
Object.keys(obj).map(function(value, index) {
   //...
});
```
to make it work properly in context of React.

**Comment by AlexGilleran** [comment]
What's the advantage over just writing `<For each="key" of={Object.keys(obj)}>` ?

Doing this would mean we'd have to put code into every for loop that checks whether it's an object or an array, so I'm pretty reticent to do it unless there's a more pressing reason than saving a few keystrokes.

**Comment by jimfb** [comment]
@AlexGilleran Agree.  `<For each="key" of={Object.keys(obj)}>` seems sufficient.

**Comment by rattrayalex** [comment]
Would `<For k="key" v="val" over="obj" >` (ie; using different props) make the implementation any simpler?

**Comment by jimfb** [comment]
Personally I would rather keep the For tag API simple and easy to understand, and let people just call `Object.keys()`, rather than introduce new syntax/props for iterating over objects instead of sets.  Otherwise, what should the tag do if you specify `k`/`v` while iterating over a list?  Throw?  Both contain the same value?  eeh, I really don't see any downside to people just using `Object.keys`.  But I do see downside to having people learn new syntax that they don't already know to use the component properly (increased learning curve).

**Comment by rattrayalex** [comment]
> Otherwise, what should the tag do if you specify k/v while iterating over a list? Throw?

Yes, it should throw. 

It's just annoying to have to both do `Object.keys` and `obj[key]`. But I'm coming from a CoffeeScript background, where easy object looping is a thing; now that I'm in ES6 (as are many others), I have to get used to `Object.keys` anyway. 

I think this is fine as-is. But it might be worth adding an example to the docs.

**Comment by jimfb** [comment]
+1 for an example of using `Object.keys` in the docs, since it's not necessarily super obvious and would be a good thing to demo.

**Comment by AlexGilleran** [comment]
Yeah that makes sense, I will get on that.

**Comment by AlexGilleran** [comment]
Documentation updated in 1.1.1

**Comment by jimfb** [comment]
Sweet!
