### ISSUE TITLE
Any way to make it work with ES7 annotations?

### ISSUE THREAD

**Issue by helarqjsc** [valtech-au/jsx-control-statements#6]
I'm using gulp for js compiling and my task looks like that:

```
gulp.task('react', function() {
    var b = browserify({
        entries: './src/application.jsx',
        extensions: ['.jsx'],
        debug: true,
        transform: [
          jsxControlStatementsify,
          babelify.configure({stage: 1}),
        ]
    });

    b.bundle().on('error', function(err) {
        $.notify().write(err.toString());
        this.emit("end");
    }).pipe(source('application.js'))
    .pipe(gulp.dest('js/'));
});
```

`jsxControlStatementsify` is copy-pasted directly from your documentation on connecting it with gulp. The problem is that I'm using annotations:

```
@reactMixin.decorate(Reflux.connect(configurationStore))
export default class Sidebar extends React.Component {
```
Which works perfectly fine with babel, but with your transformer I'm getting the following error:
```
[12:34:08] gulp-notify: [Gulp notification] while transforming somepath\components\sidebar.jsx:Error: Parse Error: Line 6: Unexpected token ILLEGAL
```
Is there are a way to make them work together?

**Comment by AlexGilleran** [comment]
The instructions with `jsControlStatementsify` are actually for if you _don't_ use Babel - I'm pretty sure what's happening there is that JSTransform (which doesn't support ES7) is being chained in front of Babel, which isn't going to work. Plus it's much neater to just use the Babel plugin.

I've never used babelify but I suspect what you want to do is something more like this:

```
transform: [
  babelify.configure({
    stage: 1
    plugins: ["jsx-control-statements/babel"]
  })
]
```

I haven't tested that though - basically you want to to use jsx-control-statements as a plugin for babel, rather than as a transformer in browserify.

**Comment by helarqjsc** [comment]
Thanks, your exact code worked fine! It would be nice to put this info into the documentation.

**Comment by AlexGilleran** [comment]
Awesome, I'll add it to the readme :)
